### ISSUE TITLE
Investigate the structure and required inputs for PopulationSim

### ISSUE THREAD

**Issue by KyTriNguyenMonash** [KyTriNguyenMonash/achilles#1]
PopulationSim is a demand generation software used to generate micro demand for a given geographic area based on open-source data such as Households Travel Survey (HTS) or Census data. In order to adapt this software for Melbourne, a basic understanding of its input and configuration are mandatory. 

## Tasks

- [x] Investigate and summarise the required inputs for PopulationSim (persons, households, control total and geo crosswalk).
- [x] Explore and list out all of the available datasets of Melbourne that we can use. Particularly, you should be able to find census, HTS and shapefile corresponding to a certain year.

Ideally, such information would be available at an SA2 or SA3 level (sometimes SA1). I would prefer them as SA2 if possible.

**Comment by bobkatla** [comment]
For the tasks:

1. There are 3 main inputs
- The seeds: households and persons. The minimum requirement would be to have the initial weight field. Also, a note for the monetary fields is that we should consider the inflation rate as well. 
-  Controls: this would be based on our chosen resolution geography (e.g: SA2). We can prep more than one controls (e.g for SA3 as well). The minimum requirement would be to specify **a control on total number of households** in each geographical unit at the lowest geographical level.
- Geography cross walk: this just to define the hierarchical structure of our chosen geographies. 

2. At our current tasks for PopSim I believe that we have the needed data from: ABS (Census), VISTA and maybe https://data.worldbank.org/ for extra data (e.g: inflation rate over the years).
